name = "nanokvm-discord-capture"
main = "target/wasm32-wasip2/release/nanokvm-discord-capture.wasm"
type = "cli"

[build]
command = "cargo build --target wasm32-wasip2 --release"

[capabilities]
wasi = true
privileged = true

[target.default]
remote = "192.168.1.143:4443"
server_name = "localhost"
client_key = "certs/client.key"

[[dependencies]]
name = "imago:nanokvm"
version = "0.1.0"
kind = "native"
wit = "oci://ghcr.io/yieldspace/imago/nanokvm@0.1.0"
